name: foxmaster-prod

services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - foxmaster-network
    env_file:
      - .env.prod
    environment:
      - DATABASE_URL=mongodb://mongo:27017/payload

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongodb_data:/data/db
    networks:
      - foxmaster-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  foxmaster-network:
    driver: bridge

volumes:
  mongodb_data:
